shared:
    image: ruby:2

jobs:
    main:
        requires: [~pr, ~commit]
        steps:
            - init: gem install bundler && bundle install
            - doctor: bundle exec rake doctor
            - build: bundle exec rake build

    publish:
        requires: [main]
        steps:
            - setup-ci: git clone https://github.com/screwdriver-cd/toolbox.git ci
            - init: gem install bundler && bundle install
            - publish: bundle exec ./deploy.sh
        secrets:
            # Pushing code to Git
            - GIT_KEY
